name: firebaseseries
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0  # Updated
  firebase_auth: ^4.8.2  # Updated
  cloud_firestore: ^4.8.2  # Updated
  firebase_storage: ^11.2.1  # Updated
  image_picker: ^0.8.7+1  # Updated
  uuid: ^3.0.7  # Updated
  firebase_messaging: ^14.6.6  # Updated

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true