// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbtTYViQ2x8dpyBnrLrBBhlfAf_PP9dJU',
    appId: '1:842186803163:android:07c97976acb43c9e5649fe',
    messagingSenderId: '842186803163',
    projectId: 'deali2',
    storageBucket: 'deali2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmbqp3x8c-harV07De0gD3LBN2TRU2faU',
    appId: '1:842186803163:ios:5575b4fef4fe12ae5649fe',
    messagingSenderId: '842186803163',
    projectId: 'deali2',
    storageBucket: 'deali2.appspot.com',
    iosBundleId: 'com.slantcode.firebaseseries',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6juzRQHiDimUYEM8wVBt81h7qjdioJgw',
    appId: '1:842186803163:web:5b903ddd5a384d905649fe',
    messagingSenderId: '842186803163',
    projectId: 'deali2',
    authDomain: 'deali2.firebaseapp.com',
    storageBucket: 'deali2.appspot.com',
    measurementId: 'G-QEX9JXNEEQ',
  );

}